dataset: [EnvPermit, Helpdesk, Sepsis, BPI2013_Closed, BPI2013_Incidents, BPI2012_C, BPI2012_WC, BPI2012_Full, BPI2012_W, Nasa]
model_config: context_ppm_exhaustive_config
cv_folds: 5
ncores: 4
train_pct: 0.8 # if cv_folds: 1 train_pct specifies the percentage of cases used for training. remaining cases are the test cases
seed: 42