base_config:
  max_pattern_size_train: [21]
  max_pattern_size_eval: [[13]]
  process_stage_width_percentage: [0.00]
  min_freq: [0.000000000000001]
  task: [['nap', 'rtp']]
  break_buffer: [1.2]
  filter_sequences: [True]
  prune_func: [None]

exhaustive_config:
  max_pattern_size_train: [21]
  max_pattern_size_eval: [[3,5,7,11,17,21]]
  process_stage_width_percentage: [0.00, 0.025, 0.10, 0.20, 0.50, 1.00]
  min_freq: [0.000000000000001]
  task: [['nap', 'rtp']]
  break_buffer: [1.2]
  filter_sequences: [True]
  prune_func: [None]

context_ppm_exhaustive_config:
  max_pattern_size_train: [21]
  max_pattern_size_eval: [[3,21]]
  process_stage_width_percentage: [1.00]
  min_freq: [0.0001]
  task: [['nep', 'sfx']]
  break_buffer: [1.2]
  filter_sequences: [True]
  embedding_type: [None]
  clustering_type: [KMeans, GaussianMixture] # GaussianMixture or KMeans
  cluster_params:
    n_clusters: [100, 50, 10, 1]
    random_state: [42]

test_config:
  max_pattern_size_train: [21]
  max_pattern_size_eval: [[3, 21]]
  process_stage_width_percentage: [1.00]
  min_freq: [0.0000001]
  task: [['nep', 'sfx']]
  break_buffer: [1.2]
  filter_sequences: [True]
  embedding_type: [None]
  clustering_type: [KMeans, GaussianMixture] # GaussianMixture or KMeans
  cluster_params:
    n_clusters: [100, 50, 10, 1]
    random_state: [42]